# Default values for Alfresco Process Services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

alfresco-process-services:
  enabled: true
  resources:
    requests:
      memory: "2000Mi"
    limits:
      memory: "3000Mi"
  nginx-ingress:
    enabled: false
  postgresql:
    persistence:
      enabled: false

alfresco-content-services:
  enabled: true
  nginx-ingress:
    enabled: false
  repository:
    image:
      repository: quay.io/alfresco/alfresco-full-content-services
      tag: "feature-AUTH-64-token-auth"
    environment:
      # The ACTIVEMQ_HOST is the DNS name of the ActiveMQ Broker. If deployed 
      # from the Alfresco ActiveMQ Chart it will be
      # <Infrastructure Release Name>-activemq-broker
      ACTIVEMQ_HOST: "<infrastructure-releasename>-activemq-broker"
      # FIXME: Port 61616 is hard-coded here, but is configurable elsewhere
      # The SYNC_SERVICE_URI should contain the details of the ingress host and port.
      SYNC_SERVICE_URI: "<ingresscontrollerurl>/syncservice"
      # The KEYCLOAK_URI should contain the details of the ingress host and port.
      KEYCLOAK_URI: "<ingresscontrollerurl>/auth"
      JAVA_OPTS: " -Dsolr.base.url=/solr
        -Dsolr.secureComms=none
        -Dindex.subsystem.name=solr6
        -Dauthentication.chain=token1:token,alfrescoNtlm1:alfrescoNtlm
        -Dtoken.authentication.enabled=true
        -Dkeycloak.auth-server-url=\"$KEYCLOAK_URI\"
        -Ddsync.service.uris=\"$SYNC_SERVICE_URI\"
        -Dmessaging.broker.url=\"failover:(tcp://${ACTIVEMQ_HOST}:61616)?timeout=3000\""
  share:
    image:
      repository: quay.io/alfresco/alfresco-full-share
      tag: "5.2.X"
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "2000Mi"
  solr:
    resources:
      requests:
        memory: "500Mi"
      limits:
        memory: "1500Mi"

alfresco-sync-service:
  enabled: false
  postgresql:
    persistence:
      enabled: false